---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=8.2.2"
license_file: LICENSE
name: iosxr
namespace: cisco
description: Ansible Network Collection for Cisco IOSXR devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.iosxr
issues: https://github.com/ansible-collections/cisco.iosxr/issues
tags: [cisco, iosxr, networking, netconf]
build_ignore:
  - .yamllint
  - .prettierignore
  - .pre-commit-config.yaml
  - .isort.cfg
  - .gitignore
  - .darglint
  - .flake8
  - .ansible-lint
  - sonar-project.properties
  - codecov.yml
  - .github/
version: "12.1.1"
