authors:
  - Ansible Network Community (ansible-network)
dependencies:
  ansible.netcommon: '>=2.5.1'
license_file: LICENSE
name: iosxr
namespace: cisco
description: Ansible Network Collection for Cisco IOSXR devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.iosxr
issues: https://github.com/ansible-collections/cisco.iosxr/issues
tags:
  - cisco
  - iosxr
  - networking
  - netconf
version: 2.1.0
