all:
  children:
    iosxr_cisshgo:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.iosxr.iosxr
        ansible_user: admin
        ansible_password: admin
        ansible_host: 127.0.0.1
        ansible_command_timeout: 200
        ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        ansible_network_cli_ssh_type: libssh
        ansible_libssh_hostkeys: +ssh-rsa
        ansible_become: false
      children:
        iosxr_lacp_gathered:
          hosts:
            cisshgo-lacp-gathered:
              ansible_port: 10000
        iosxr_lacp_merged:
          hosts:
            cisshgo-lacp-merged:
              ansible_port: 10001
        iosxr_lacp_replaced:
          hosts:
            cisshgo-lacp-replaced:
              ansible_port: 10002
        iosxr_lacp_deleted:
          hosts:
            cisshgo-lacp-deleted:
              ansible_port: 10003
