# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the iosxr_bgp_address_family module
"""


class Bgp_address_familyArgs(object):  # pylint: disable=R0903
    """The arg spec for the iosxr_bgp_address_family module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "AS_number": {"type": "str"},
                "address_family": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "afi": {
                            "type": "str",
                            "choices": [
                                "ipv4",
                                "ipv6",
                                "l2vpn",
                                "link-state",
                                "vvpnv4",
                                "vpnv6",
                            ],
                        },
                        "af_modifier": {
                            "type": "str",
                            "choices": [
                                "flowspec",
                                "mdt",
                                "multicast",
                                "mvpn",
                                "rt-filter",
                                "tunnel",
                                "unicast",
                                "evpn",
                                "mspw",
                                "vpls-vpws",
                                "link-state",
                            ],
                        },
                        "additional_paths": {
                            "type": "str",
                            "choices": ["send", "receive"],
                        },
                        "advertise_best_external": {"type": "bool"},
                        "aggregate_address": {
                            "type": "dict",
                            "options": {
                                "value": {"type": "str"},
                                "as_set": {"type": "bool"},
                                "as_confed_set": {"type": "bool"},
                                "summery_only": {"type": "bool"},
                                "route_policy": {"type": "str"},
                            },
                        },
                        "allocate_label": {
                            "type": "dict",
                            "options": {
                                "all": {"type": "bool"},
                                "route_policy": {"type": "str"},
                            },
                        },
                        "as_path_loopcheck_out_disable": {"type": "bool"},
                        "bgp": {
                            "type": "dict",
                            "options": {
                                "attribute_download": {"type": "bool"},
                                "bestpath": {
                                    "type": "dict",
                                    "options": {
                                        "origin_as": {
                                            "type": "dict",
                                            "options": {
                                                "use": {
                                                    "type": "dict",
                                                    "options": {
                                                        "validity": {
                                                            "type": "bool"
                                                        }
                                                    },
                                                },
                                                "allow": {
                                                    "type": "dict",
                                                    "options": {
                                                        "invalid": {"type": "bool"}
                                                    },
                                                },
                                            },
                                        }
                                    },
                                },
                                "client_to_client": {
                                    "type": "dict",
                                    "options": {
                                        "reflection_disable": {"type": "bool"},
                                        "reflection": {
                                            "type": "dict",
                                            "options": {
                                                "cluster_id": {"type": "str"},
                                                "disable": {"type": "bool"},
                                            },
                                        },
                                    },
                                },
                                "dampening": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "value": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "label_delay": {
                                    "type": "dict",
                                    "options": {
                                        "delay_second_parts": {"type": "int"},
                                        "delay_ms_parts": {"type": "int"},
                                    },
                                },
                                "import_delay": {
                                    "type": "dict",
                                    "options": {
                                        "delay_second_parts": {"type": "int"},
                                        "delay_ms_parts": {"type": "int"},
                                    },
                                },
                                "origin_as": {
                                    "type": "dict",
                                    "options": {
                                        "validation": {
                                            "type": "dict",
                                            "options": {
                                                "disable": {"type": "bool"},
                                                "signal": {
                                                    "type": "dict",
                                                    "options": {
                                                        "ibgp": {"type": "bool"}
                                                    },
                                                },
                                            },
                                        }
                                    },
                                },
                                "scan_time": {"type": "int"},
                            },
                        },
                        "default_martian_check_disable": {"type": "bool"},
                        "distance": {
                            "type": "dict",
                            "options": {
                                "routes_external_to_as": {"type": "int"},
                                "routes_internal_to_as": {"type": "int"},
                                "local_routes": {"type": "int"},
                            },
                        },
                        "dynamic_med": {"type": "int"},
                        "maximum_paths": {
                            "type": "dict",
                            "options": {
                                "ibgp": {
                                    "type": "dict",
                                    "options": {
                                        "max_path_value": {"type": "int"},
                                        "order_igp_metric": {"type": "bool"},
                                        "selective_order_igp_metric": {
                                            "type": "bool"
                                        },
                                        "unequal_cost": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "selective_order_igp_metric": {
                                                    "type": "bool"
                                                },
                                            },
                                        },
                                    },
                                },
                                "ebgp": {
                                    "type": "dict",
                                    "options": {
                                        "max_path_value": {"type": "int"},
                                        "order_igp_metric": {"type": "bool"},
                                        "selective_order_igp_metric": {
                                            "type": "bool"
                                        },
                                        "unequal_cost": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "selective_order_igp_metric": {
                                                    "type": "bool"
                                                },
                                            },
                                        },
                                    },
                                },
                                "eibgp": {
                                    "type": "dict",
                                    "options": {
                                        "max_path_value": {"type": "int"},
                                        "order_igp_metric": {"type": "bool"},
                                        "selective_order_igp_metric": {
                                            "type": "bool"
                                        },
                                    },
                                },
                            },
                        },
                        "network": {
                            "type": "dict",
                            "options": {
                                "value": {"type": "str"},
                                "backdoor_route_policy": {"type": "str"},
                                "route_policy": {"type": "str"},
                            },
                        },
                        "nexthop": {
                            "type": "dict",
                            "options": {
                                "resolution_prefix-length_minimum": {
                                    "type": "int",
                                    "choices": [0, 32],
                                },
                                "route_policy": {"type": "str"},
                                "trigger_delay_critical": {"type": "int"},
                                "trigger_delay_non_critical": {"type": "int"},
                            },
                        },
                        "optimal_route_reflection": {
                            "type": "dict",
                            "options": {
                                "group_name": {"type": "str"},
                                "primary_address": {"type": "str"},
                                "secondary_address": {"type": "str"},
                            },
                        },
                        "permanent_network_route_policy": {"type": "str"},
                        "retain_local_label": {"type": "int"},
                        "table_policy": {"type": "str"},
                        "update": {
                            "type": "dict",
                            "options": {
                                "limit": {
                                    "type": "dict",
                                    "options": {
                                        "address_family": {
                                            "type": "dict",
                                            "options": {
                                                "ibgp": {"type": "int"},
                                                "ebgp": {"type": "int"},
                                            },
                                        },
                                        "sub_group": {"type": "int"},
                                    },
                                },
                                "wait_install": {"type": "bool"},
                            },
                        },
                        "redistribute": {
                            "type": "dict",
                            "options": {
                                "application": {
                                    "type": "dict",
                                    "options": {
                                        "name": {"type": "str"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "connected": {
                                    "type": "dict",
                                    "options": {
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "eigrp": {
                                    "type": "dict",
                                    "options": {
                                        "name": {"type": "str"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                        "internal": {"type": "bool"},
                                        "external": {"type": "bool"},
                                    },
                                },
                                "isis": {
                                    "type": "dict",
                                    "options": {
                                        "name": {"type": "str"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                        "level": {
                                            "type": "str",
                                            "choices": ["1", "2", "1-inter-area"],
                                        },
                                    },
                                },
                                "lisp": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "mobile": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "ospf": {
                                    "type": "dict",
                                    "options": {
                                        "name": {"type": "str"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                        "internal": {"type": "bool"},
                                        "nssa_external": {"type": "bool"},
                                        "external": {
                                            "type": "int",
                                            "choices": [1, 2],
                                        },
                                    },
                                },
                                "rip": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "static": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "subscriber": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "metric": {"type": "int"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                            },
                        },
                        "inter_as_install": {"type": "bool"},
                        "segmented_multicast": {"type": "bool"},
                        "global_table_multicast": {"type": "bool"},
                        "vrf_all": {
                            "type": "dict",
                            "options": {
                                "source_rt_import_policy": {"type": "bool"},
                                "table_policy": {"type": "str"},
                                "label_mode": {
                                    "type": "dict",
                                    "options": {
                                        "per_ce": {"type": "bool"},
                                        "per_vrf": {"type": "bool"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                            },
                        },
                        "weight": {
                            "type": "dict",
                            "options": {
                                "reset_on_import_disable": {"type": "bool"},
                                "reset_on_import": {"type": "bool"},
                            },
                        },
                    },
                },
                "vrfs": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "vrf_name": {"type": "str"},
                        "address_family": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "afi": {
                                    "type": "str",
                                    "choices": ["ipv4", "ipv6"],
                                },
                                "af_type": {
                                    "type": "str",
                                    "choices": [
                                        "unicast",
                                        "multicast",
                                        "flowspec",
                                        "mvpn",
                                    ],
                                },
                                "additional_paths": {
                                    "type": "str",
                                    "choices": ["send", "receive"],
                                },
                                "advertise_best_external": {"type": "bool"},
                                "as_path_loopcheck_out_disable": {"type": "bool"},
                                "aggrigate_address": {
                                    "type": "dict",
                                    "options": {
                                        "value": {"type": "str"},
                                        "as_set": {"type": "bool"},
                                        "as_confed_set": {"type": "bool"},
                                        "summery_only": {"type": "bool"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "allocate_label": {
                                    "type": "dict",
                                    "options": {
                                        "all": {"type": "bool"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "allow_vpn_default_originate": {"type": "bool"},
                                "bgp": {
                                    "type": "dict",
                                    "options": {
                                        "dampening": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "value": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "attribute_download": {"type": "bool"},
                                    },
                                },
                                "nexthop": {
                                    "type": "dict",
                                    "options": {
                                        "resolution_prefix-length_minimum": {
                                            "type": "int",
                                            "choices": [0, 32],
                                        },
                                        "route_policy": {"type": "str"},
                                        "trigger_delay_critical": {"type": "int"},
                                        "trigger_delay_non_critical": {
                                            "type": "int"
                                        },
                                    },
                                },
                                "distance": {
                                    "type": "dict",
                                    "options": {
                                        "routes_external_to_as": {"type": "int"},
                                        "routes_internal_to_as": {"type": "int"},
                                        "local_routes": {"type": "int"},
                                    },
                                },
                                "dynamic_med": {"type": "int"},
                                "label_mode": {
                                    "type": "dict",
                                    "options": {
                                        "per_ce": {"type": "bool"},
                                        "per_vrf": {"type": "bool"},
                                        "route_policy": {"type": "str"},
                                        "per_prefix": {"type": "bool"},
                                    },
                                },
                                "maximum_paths": {
                                    "type": "dict",
                                    "options": {
                                        "ibgp": {
                                            "type": "dict",
                                            "options": {
                                                "max_path_value": {"type": "int"},
                                                "order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "selective_order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "unequal_cost": {
                                                    "type": "dict",
                                                    "options": {
                                                        "set": {"type": "bool"},
                                                        "order_igp_metric": {
                                                            "type": "bool"
                                                        },
                                                        "selective_order_igp_metric": {
                                                            "type": "bool"
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                        "ebgp": {
                                            "type": "dict",
                                            "options": {
                                                "max_path_value": {"type": "int"},
                                                "order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "selective_order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "unequal_cost": {
                                                    "type": "dict",
                                                    "options": {
                                                        "set": {"type": "bool"},
                                                        "order_igp_metric": {
                                                            "type": "bool"
                                                        },
                                                        "selective_order_igp_metric": {
                                                            "type": "bool"
                                                        },
                                                    },
                                                },
                                            },
                                        },
                                        "eibgp": {
                                            "type": "dict",
                                            "options": {
                                                "max_path_value": {"type": "int"},
                                                "order_igp_metric": {
                                                    "type": "bool"
                                                },
                                                "selective_order_igp_metric": {
                                                    "type": "bool"
                                                },
                                            },
                                        },
                                    },
                                },
                                "mvpn_single_forwarder_selection_all": {
                                    "type": "bool"
                                },
                                "mvpn_single_forwarder_selection_highest_ip_address": {
                                    "type": "bool"
                                },
                                "network": {
                                    "type": "dict",
                                    "options": {
                                        "value": {"type": "str"},
                                        "backdoor_route_policy": {"type": "str"},
                                        "route_policy": {"type": "str"},
                                    },
                                },
                                "optimal_route_reflection": {
                                    "type": "dict",
                                    "options": {
                                        "group_name": {"type": "str"},
                                        "primary_address": {"type": "str"},
                                        "secondary_address": {"type": "str"},
                                    },
                                },
                                "redistribute": {
                                    "type": "dict",
                                    "options": {
                                        "application": {
                                            "type": "dict",
                                            "options": {
                                                "name": {"type": "str"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "connected": {
                                            "type": "dict",
                                            "options": {
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "eigrp": {
                                            "type": "dict",
                                            "options": {
                                                "name": {"type": "str"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                                "internal": {"type": "bool"},
                                                "external": {"type": "bool"},
                                            },
                                        },
                                        "isis": {
                                            "type": "dict",
                                            "options": {
                                                "name": {"type": "str"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                                "level": {
                                                    "type": "str",
                                                    "choices": [
                                                        "1",
                                                        "2",
                                                        "1-inter-area",
                                                    ],
                                                },
                                            },
                                        },
                                        "lisp": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "mobile": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "ospf": {
                                            "type": "dict",
                                            "options": {
                                                "name": {"type": "str"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                                "internal": {"type": "bool"},
                                                "nssa_external": {"type": "bool"},
                                                "external": {
                                                    "type": "int",
                                                    "choices": [1, 2],
                                                },
                                            },
                                        },
                                        "rip": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "static": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                        "subscriber": {
                                            "type": "dict",
                                            "options": {
                                                "set": {"type": "bool"},
                                                "metric": {"type": "int"},
                                                "route_policy": {"type": "str"},
                                            },
                                        },
                                    },
                                },
                                "table_policy": {"type": "str"},
                                "route_target_download": {"type": "bool"},
                                "weight": {
                                    "type": "dict",
                                    "options": {
                                        "reset_on_import_disable": {
                                            "type": "bool"
                                        },
                                        "reset_on_import": {"type": "bool"},
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "deleted",
                "merged",
                "overridden",
                "replaced",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
