devices:
- platform: iosxr_l3_interfaces
  count: 1
- scenario: iosxr-l3-interfaces-merged
  count: 1
- scenario: iosxr-l3-interfaces-replaced
  count: 1
- scenario: iosxr-l3-interfaces-overridden
  count: 1
- scenario: iosxr-l3-interfaces-deleted
  count: 1
