# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ems_grpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
# Optional runtime dependency: allow Ansible sanity to import this module.
try:
    from google.protobuf import descriptor as _descriptor
    from google.protobuf import descriptor_pool as _descriptor_pool
    from google.protobuf import symbol_database as _symbol_database
    from google.protobuf.internal import builder as _builder

    # @@protoc_insertion_point(imports)

    _sym_db = _symbol_database.Default()

    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
        b'\n\x0eems_grpc.proto\x12"IOSXRE'
        b"xtensibleManagabilitySer"
        b'vice"4\n\rConfigGetArgs\x12\r\n'
        b"\x05ReqId\x18\x01 \x01(\x03\x12\x14\n\x0cyangpath"
        b'json\x18\x02 \x01(\t"D\n\x0eConfigGetR'
        b"eply\x12\x10\n\x08ResReqId\x18\x01 \x01(\x03\x12\x10"
        b"\n\x08yangjson\x18\x02 \x01(\t\x12\x0e\n\x06erro"
        b'rs\x18\x03 \x01(\t"2\n\x0bGetOperArgs\x12'
        b"\r\n\x05ReqId\x18\x01 \x01(\x03\x12\x14\n\x0cyangpa"
        b'thjson\x18\x02 \x01(\t"B\n\x0cGetOperR'
        b"eply\x12\x10\n\x08ResReqId\x18\x01 \x01(\x03\x12\x10"
        b"\n\x08yangjson\x18\x02 \x01(\t\x12\x0e\n\x06erro"
        b'rs\x18\x03 \x01(\t"-\n\nConfigArgs\x12\r'
        b"\n\x05ReqId\x18\x01 \x01(\x03\x12\x10\n\x08yangjso"
        b'n\x18\x02 \x01(\t"/\n\x0bConfigReply\x12\x10'
        b"\n\x08ResReqId\x18\x01 \x01(\x03\x12\x0e\n\x06erro"
        b'rs\x18\x02 \x01(\t"+\n\rCliConfigArg'
        b"s\x12\r\n\x05ReqId\x18\x01 \x01(\x03\x12\x0b\n\x03cli\x18"
        b'\x02 \x01(\t"2\n\x0eCliConfigReply\x12'
        b"\x10\n\x08ResReqId\x18\x01 \x01(\x03\x12\x0e\n\x06err"
        b'ors\x18\x02 \x01(\t"A\n\x11CommitRepla'
        b"ceArgs\x12\r\n\x05ReqId\x18\x01 \x01(\x03\x12\x0b\n"
        b"\x03cli\x18\x02 \x01(\t\x12\x10\n\x08yangjson\x18\x03"
        b' \x01(\t"6\n\x12CommitReplaceRep'
        b"ly\x12\x10\n\x08ResReqId\x18\x01 \x01(\x03\x12\x0e\n\x06"
        b'errors\x18\x02 \x01(\t"+\n\tCommitMs'
        b"g\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0f\n\x07comm"
        b'ent\x18\x02 \x01(\t"W\n\nCommitArgs\x12'
        b":\n\x03msg\x18\x01 \x01(\x0b2-.IOSXRExte"
        b"nsibleManagabilityServic"
        b"e.CommitMsg\x12\r\n\x05ReqId\x18\x02 \x01"
        b'(\x03"q\n\x0bCommitReply\x12@\n\x06res'
        b"ult\x18\x01 \x01(\x0e20.IOSXRExtensi"
        b"bleManagabilityService.C"
        b"ommitResult\x12\x10\n\x08ResReqId\x18"
        b'\x02 \x01(\x03\x12\x0e\n\x06errors\x18\x03 \x01(\t"#\n'
        b"\x12DiscardChangesArgs\x12\r\n\x05R"
        b'eqId\x18\x01 \x01(\x03"7\n\x13DiscardCha'
        b"ngesReply\x12\x10\n\x08ResReqId\x18\x01 "
        b'\x01(\x03\x12\x0e\n\x06errors\x18\x02 \x01(\t")\n\x0bS'
        b"howCmdArgs\x12\r\n\x05ReqId\x18\x01 \x01("
        b'\x03\x12\x0b\n\x03cli\x18\x02 \x01(\t"D\n\x10ShowCm'
        b"dTextReply\x12\x10\n\x08ResReqId\x18\x01"
        b" \x01(\x03\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x0e\n\x06"
        b'errors\x18\x03 \x01(\t"H\n\x10ShowCmdJ'
        b"SONReply\x12\x10\n\x08ResReqId\x18\x01 \x01"
        b"(\x03\x12\x12\n\njsonoutput\x18\x02 \x01(\t\x12\x0e"
        b'\n\x06errors\x18\x03 \x01(\t"A\n\x0eCreate'
        b"SubsArgs\x12\r\n\x05ReqId\x18\x01 \x01(\x03\x12"
        b"\x0e\n\x06encode\x18\x02 \x01(\x03\x12\x10\n\x08subid"
        b'str\x18\x03 \x01(\t"A\n\x0fCreateSubsR'
        b"eply\x12\x10\n\x08ResReqId\x18\x01 \x01(\x03\x12\x0c"
        b"\n\x04data\x18\x02 \x01(\x0c\x12\x0e\n\x06errors\x18\x03"
        b" \x01(\t*3\n\x0cCommitResult\x12\n\n\x06"
        b"CHANGE\x10\x00\x12\r\n\tNO_CHANGE\x10\x01\x12"
        b"\x08\n\x04FAIL\x10\x022\xb1\t\n\x0egRPCConfig"
        b"Oper\x12t\n\tGetConfig\x121.IOSX"
        b"RExtensibleManagabilityS"
        b"ervice.ConfigGetArgs\x1a2.I"
        b"OSXRExtensibleManagabili"
        b"tyService.ConfigGetReply"
        b"0\x01\x12n\n\x0bMergeConfig\x12..IOSX"
        b"RExtensibleManagabilityS"
        b"ervice.ConfigArgs\x1a/.IOSX"
        b"RExtensibleManagabilityS"
        b"ervice.ConfigReply\x12o\n\x0cDe"
        b"leteConfig\x12..IOSXRExtens"
        b"ibleManagabilityService."
        b"ConfigArgs\x1a/.IOSXRExtens"
        b"ibleManagabilityService."
        b"ConfigReply\x12p\n\rReplaceCo"
        b"nfig\x12..IOSXRExtensibleMa"
        b"nagabilityService.Config"
        b"Args\x1a/.IOSXRExtensibleMa"
        b"nagabilityService.Config"
        b"Reply\x12r\n\tCliConfig\x121.IOS"
        b"XRExtensibleManagability"
        b"Service.CliConfigArgs\x1a2."
        b"IOSXRExtensibleManagabil"
        b"ityService.CliConfigRepl"
        b"y\x12~\n\rCommitReplace\x125.IOS"
        b"XRExtensibleManagability"
        b"Service.CommitReplaceArg"
        b"s\x1a6.IOSXRExtensibleManag"
        b"abilityService.CommitRep"
        b"laceReply\x12o\n\x0cCommitConfi"
        b"g\x12..IOSXRExtensibleManag"
        b"abilityService.CommitArg"
        b"s\x1a/.IOSXRExtensibleManag"
        b"abilityService.CommitRep"
        b"ly\x12\x87\x01\n\x14ConfigDiscardChan"
        b"ges\x126.IOSXRExtensibleMan"
        b"agabilityService.Discard"
        b"ChangesArgs\x1a7.IOSXRExten"
        b"sibleManagabilityService"
        b".DiscardChangesReply\x12n\n\x07"
        b"GetOper\x12/.IOSXRExtensibl"
        b"eManagabilityService.Get"
        b"OperArgs\x1a0.IOSXRExtensib"
        b"leManagabilityService.Ge"
        b"tOperReply0\x01\x12w\n\nCreateSu"
        b"bs\x122.IOSXRExtensibleMana"
        b"gabilityService.CreateSu"
        b"bsArgs\x1a3.IOSXRExtensible"
        b"ManagabilityService.Crea"
        b"teSubsReply0\x012\x86\x02\n\x08gRPCEx"
        b"ec\x12|\n\x11ShowCmdTextOutput\x12"
        b"/.IOSXRExtensibleManagab"
        b"ilityService.ShowCmdArgs"
        b"\x1a4.IOSXRExtensibleManaga"
        b"bilityService.ShowCmdTex"
        b"tReply0\x01\x12|\n\x11ShowCmdJSONO"
        b"utput\x12/.IOSXRExtensibleM"
        b"anagabilityService.ShowC"
        b"mdArgs\x1a4.IOSXRExtensible"
        b"ManagabilityService.Show"
        b"CmdJSONReply0\x01b\x06proto3",
    )

    _globals = globals()
    _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ems_grpc_pb2", _globals)
    if not _descriptor._USE_C_DESCRIPTORS:  # pragma: no cover
        DESCRIPTOR._loaded_options = None
        _globals["_COMMITRESULT"]._serialized_start = 1278
        _globals["_COMMITRESULT"]._serialized_end = 1329
        _globals["_CONFIGGETARGS"]._serialized_start = 54
        _globals["_CONFIGGETARGS"]._serialized_end = 106
        _globals["_CONFIGGETREPLY"]._serialized_start = 108
        _globals["_CONFIGGETREPLY"]._serialized_end = 176
        _globals["_GETOPERARGS"]._serialized_start = 178
        _globals["_GETOPERARGS"]._serialized_end = 228
        _globals["_GETOPERREPLY"]._serialized_start = 230
        _globals["_GETOPERREPLY"]._serialized_end = 296
        _globals["_CONFIGARGS"]._serialized_start = 298
        _globals["_CONFIGARGS"]._serialized_end = 343
        _globals["_CONFIGREPLY"]._serialized_start = 345
        _globals["_CONFIGREPLY"]._serialized_end = 392
        _globals["_CLICONFIGARGS"]._serialized_start = 394
        _globals["_CLICONFIGARGS"]._serialized_end = 437
        _globals["_CLICONFIGREPLY"]._serialized_start = 439
        _globals["_CLICONFIGREPLY"]._serialized_end = 489
        _globals["_COMMITREPLACEARGS"]._serialized_start = 491
        _globals["_COMMITREPLACEARGS"]._serialized_end = 556
        _globals["_COMMITREPLACEREPLY"]._serialized_start = 558
        _globals["_COMMITREPLACEREPLY"]._serialized_end = 612
        _globals["_COMMITMSG"]._serialized_start = 614
        _globals["_COMMITMSG"]._serialized_end = 657
        _globals["_COMMITARGS"]._serialized_start = 659
        _globals["_COMMITARGS"]._serialized_end = 746
        _globals["_COMMITREPLY"]._serialized_start = 748
        _globals["_COMMITREPLY"]._serialized_end = 861
        _globals["_DISCARDCHANGESARGS"]._serialized_start = 863
        _globals["_DISCARDCHANGESARGS"]._serialized_end = 898
        _globals["_DISCARDCHANGESREPLY"]._serialized_start = 900
        _globals["_DISCARDCHANGESREPLY"]._serialized_end = 955
        _globals["_SHOWCMDARGS"]._serialized_start = 957
        _globals["_SHOWCMDARGS"]._serialized_end = 998
        _globals["_SHOWCMDTEXTREPLY"]._serialized_start = 1000
        _globals["_SHOWCMDTEXTREPLY"]._serialized_end = 1068
        _globals["_SHOWCMDJSONREPLY"]._serialized_start = 1070
        _globals["_SHOWCMDJSONREPLY"]._serialized_end = 1142
        _globals["_CREATESUBSARGS"]._serialized_start = 1144
        _globals["_CREATESUBSARGS"]._serialized_end = 1209
        _globals["_CREATESUBSREPLY"]._serialized_start = 1211
        _globals["_CREATESUBSREPLY"]._serialized_end = 1276
        _globals["_GRPCCONFIGOPER"]._serialized_start = 1332
        _globals["_GRPCCONFIGOPER"]._serialized_end = 2533
        _globals["_GRPCEXEC"]._serialized_start = 2536
        _globals["_GRPCEXEC"]._serialized_end = 2798
    # @@protoc_insertion_point(module_scope)
except ImportError:
    pass
