# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
# Optional runtime dependency: allow Ansible sanity to import this module.
try:
    import grpc

    from . import ems_grpc_pb2 as ems__grpc__pb2

    class GrpcConfigOperStub:
        """Missing associated documentation comment in .proto file."""

        def __init__(self, channel):
            """Constructor.

            Args:
                channel: A grpc.Channel.
            """
            self.get_config = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetConfig",
                request_serializer=ems__grpc__pb2.ConfigGetArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigGetReply.FromString,
            )
            self.merge_config = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig",
                request_serializer=ems__grpc__pb2.ConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigReply.FromString,
            )
            self.delete_config = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig",
                request_serializer=ems__grpc__pb2.ConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigReply.FromString,
            )
            self.replace_config = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig",
                request_serializer=ems__grpc__pb2.ConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ConfigReply.FromString,
            )
            self.cli_config = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig",
                request_serializer=ems__grpc__pb2.CliConfigArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CliConfigReply.FromString,
            )
            self.commit_replace = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace",
                request_serializer=ems__grpc__pb2.CommitReplaceArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CommitReplaceReply.FromString,
            )
            self.commit_config = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig",
                request_serializer=ems__grpc__pb2.CommitArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CommitReply.FromString,
            )
            self.config_discard_changes = channel.unary_unary(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges",
                request_serializer=ems__grpc__pb2.DiscardChangesArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.DiscardChangesReply.FromString,
            )
            self.get_oper = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetOper",
                request_serializer=ems__grpc__pb2.GetOperArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.GetOperReply.FromString,
            )
            self.create_subs = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CreateSubs",
                request_serializer=ems__grpc__pb2.CreateSubsArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.CreateSubsReply.FromString,
            )

    class GrpcConfigOperServicer:
        """Missing associated documentation comment in .proto file."""

        def get_config(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def merge_config(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def delete_config(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def replace_config(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def cli_config(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def commit_replace(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def commit_config(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def config_discard_changes(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def get_oper(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def create_subs(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

    def add_grpc_config_oper_servicer_to_server(servicer, server):
        rpc_method_handlers = {
            "GetConfig": grpc.unary_stream_rpc_method_handler(
                servicer.get_config,
                request_deserializer=ems__grpc__pb2.ConfigGetArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigGetReply.SerializeToString,
            ),
            "MergeConfig": grpc.unary_unary_rpc_method_handler(
                servicer.merge_config,
                request_deserializer=ems__grpc__pb2.ConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigReply.SerializeToString,
            ),
            "DeleteConfig": grpc.unary_unary_rpc_method_handler(
                servicer.delete_config,
                request_deserializer=ems__grpc__pb2.ConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigReply.SerializeToString,
            ),
            "ReplaceConfig": grpc.unary_unary_rpc_method_handler(
                servicer.replace_config,
                request_deserializer=ems__grpc__pb2.ConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.ConfigReply.SerializeToString,
            ),
            "CliConfig": grpc.unary_unary_rpc_method_handler(
                servicer.cli_config,
                request_deserializer=ems__grpc__pb2.CliConfigArgs.FromString,
                response_serializer=ems__grpc__pb2.CliConfigReply.SerializeToString,
            ),
            "CommitReplace": grpc.unary_unary_rpc_method_handler(
                servicer.commit_replace,
                request_deserializer=ems__grpc__pb2.CommitReplaceArgs.FromString,
                response_serializer=ems__grpc__pb2.CommitReplaceReply.SerializeToString,
            ),
            "CommitConfig": grpc.unary_unary_rpc_method_handler(
                servicer.commit_config,
                request_deserializer=ems__grpc__pb2.CommitArgs.FromString,
                response_serializer=ems__grpc__pb2.CommitReply.SerializeToString,
            ),
            "ConfigDiscardChanges": grpc.unary_unary_rpc_method_handler(
                servicer.config_discard_changes,
                request_deserializer=ems__grpc__pb2.DiscardChangesArgs.FromString,
                response_serializer=ems__grpc__pb2.DiscardChangesReply.SerializeToString,
            ),
            "GetOper": grpc.unary_stream_rpc_method_handler(
                servicer.get_oper,
                request_deserializer=ems__grpc__pb2.GetOperArgs.FromString,
                response_serializer=ems__grpc__pb2.GetOperReply.SerializeToString,
            ),
            "CreateSubs": grpc.unary_stream_rpc_method_handler(
                servicer.create_subs,
                request_deserializer=ems__grpc__pb2.CreateSubsArgs.FromString,
                response_serializer=ems__grpc__pb2.CreateSubsReply.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            "IOSXRExtensibleManagabilityService.gRPCConfigOper",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))

    # This class is part of an EXPERIMENTAL API.
    class GrpcConfigOper:
        """Missing associated documentation comment in .proto file."""

        @staticmethod
        def get_config(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetConfig",
                ems__grpc__pb2.ConfigGetArgs.SerializeToString,
                ems__grpc__pb2.ConfigGetReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def merge_config(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig",
                ems__grpc__pb2.ConfigArgs.SerializeToString,
                ems__grpc__pb2.ConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def delete_config(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig",
                ems__grpc__pb2.ConfigArgs.SerializeToString,
                ems__grpc__pb2.ConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def replace_config(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig",
                ems__grpc__pb2.ConfigArgs.SerializeToString,
                ems__grpc__pb2.ConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def cli_config(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig",
                ems__grpc__pb2.CliConfigArgs.SerializeToString,
                ems__grpc__pb2.CliConfigReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def commit_replace(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace",
                ems__grpc__pb2.CommitReplaceArgs.SerializeToString,
                ems__grpc__pb2.CommitReplaceReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def commit_config(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig",
                ems__grpc__pb2.CommitArgs.SerializeToString,
                ems__grpc__pb2.CommitReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def config_discard_changes(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_unary(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges",
                ems__grpc__pb2.DiscardChangesArgs.SerializeToString,
                ems__grpc__pb2.DiscardChangesReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def get_oper(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetOper",
                ems__grpc__pb2.GetOperArgs.SerializeToString,
                ems__grpc__pb2.GetOperReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def create_subs(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CreateSubs",
                ems__grpc__pb2.CreateSubsArgs.SerializeToString,
                ems__grpc__pb2.CreateSubsReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

    class GrpcExecStub:
        """Missing associated documentation comment in .proto file."""

        def __init__(self, channel):
            """Constructor.

            Args:
                channel: A grpc.Channel.
            """
            self.show_cmd_text_output = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdTextOutput",
                request_serializer=ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ShowCmdTextReply.FromString,
            )
            self.show_cmd_json_output = channel.unary_stream(
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdJSONOutput",
                request_serializer=ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                response_deserializer=ems__grpc__pb2.ShowCmdJSONReply.FromString,
            )

    class GrpcExecServicer:
        """Missing associated documentation comment in .proto file."""

        def show_cmd_text_output(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

        def show_cmd_json_output(self, request, context):
            """Missing associated documentation comment in .proto file."""
            del request
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

    def add_grpc_exec_servicer_to_server(servicer, server):
        rpc_method_handlers = {
            "ShowCmdTextOutput": grpc.unary_stream_rpc_method_handler(
                servicer.show_cmd_text_output,
                request_deserializer=ems__grpc__pb2.ShowCmdArgs.FromString,
                response_serializer=ems__grpc__pb2.ShowCmdTextReply.SerializeToString,
            ),
            "ShowCmdJSONOutput": grpc.unary_stream_rpc_method_handler(
                servicer.show_cmd_json_output,
                request_deserializer=ems__grpc__pb2.ShowCmdArgs.FromString,
                response_serializer=ems__grpc__pb2.ShowCmdJSONReply.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            "IOSXRExtensibleManagabilityService.gRPCExec",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))

    # This class is part of an EXPERIMENTAL API.
    class GrpcExec:
        """Missing associated documentation comment in .proto file."""

        @staticmethod
        def show_cmd_text_output(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdTextOutput",
                ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                ems__grpc__pb2.ShowCmdTextReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

        @staticmethod
        def show_cmd_json_output(
            request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None,
        ):
            return grpc.experimental.unary_stream(
                request,
                target,
                "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdJSONOutput",
                ems__grpc__pb2.ShowCmdArgs.SerializeToString,
                ems__grpc__pb2.ShowCmdJSONReply.FromString,
                options,
                channel_credentials,
                insecure,
                call_credentials,
                compression,
                wait_for_ready,
                timeout,
                metadata,
            )

except ImportError:
    pass
