#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2020 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for iosxr_ospfv2
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = """
---
module: iosxr_ospfv2
version_added: 1.0.0
short_description: OSPFv2 resource module.
description: 
  - This module manages global OSPFv2 configuration on devices running Cisco IOS-XR.
author: Rohit Thakur (@rohitthakur2590)
options:
  config:
    description: A list of OSPF process configuration
    type: dict
    suboptions:
      processes: 
        description: A list of OSPF instances configuration
        type: list
        elements: dict
        suboptions:
          address_family_unicast:
            description: Enable unicast topology for ipv4 address family.
            type: bool
          adjacency_stagger:
            description: Stagger OSPF adjacency bring up
            type: dict
            suboptions:
              min_adjacency:
                description: Initial number of neighbors to bring up per area (default 2)
                type: int
              max_adjacency:
                description: Maximum simultaneous neighbors to bring up (default 64)
                type: int
              disable:
                description: Disable stagger OSPF adjacency
                type: bool
          authentication:
            description: Enable authentication.
            type: dict
            suboptions:
              keychain:
                description: Specify keychain name.
                type: str
              message_digest:
                description: Use message-digest authentication.
                type: dict
                suboptions:
                  set:
                    description: Specify message-digest selection.
                    type: bool
                  keychain:
                    description: Specify keychain name.
                    type: str
              no_auth:
                description: Use no authentication.
                type: bool
          apply_weight:
            description: Enable weights configured under interfaces for load sharing.
            type: dict
            suboptions:
              bandwidth:
                description: Reference bandwidth to use for calculation (Mbits/sec)
                type: int
              default_weight:
                description: Specify default weight value to use when it is not configured under interface
                type: int
          areas:
            description: Configure OSPF areas' properties
            type: list
            elements: dict
            suboptions:
              area_id:
                description: Area ID as IP address or integer
                type: str
                required: True
              authentication:
                description: Enable authentication
                type: dict
                suboptions:
                  keychain:
                    description: Specify keychain name
                    type: str
                  message_digest:
                    description: Use message-digest authentication
                    type: dict
                    suboptions:
                      keychain:
                        description: Specify keychain name
                        type: str
                  no_auth:
                    description: Use no authentication
                    type: bool
              authentication_key:
                description: Used to mention authentication password (key).
                type: dict
                suboptions:
                  password:
                    description: The OSPF password (key)
                    type: str
                  clear:
                    description: Specifies an UNENCRYPTED password (key) will follow
                    type: str
                  encrypted:
                    description: Specifies an ENCRYPTED password (key) will follow
                    type: str
              default_cost:
                description: Set the summary default-cost of a NSSA/stub area. Stub's advertised external route metric (1-16777215).
                type: int
              cost:
                description: Interface cost (1-65535).
                type: int
              dead_interval:
                description: Interval after which a neighbor is declared dead (<1-65535> seconds).
                type: int
              hello_interval:
                description: Time between HELLO packets (<1-65535> seconds).
                type: int
              transmit_delay:
                description: Estimated time needed to send link-state update packet (<1-65535> seconds).
                type: int
              mpls:
                description: Configure MPLS routing protocol parameters.
                type: dict
                suboptions:
                  traffic_eng:
                    description: Configure an ospf area to run MPLS Traffic Engineering.
                    type: bool  
                  ldp:
                    description: Configure LDP parameters.
                    type: dict
                    suboptions:
                      auto_config:
                        description: Enable LDP IGP interface auto-configuration.
                        type: bool
                      sync:
                        description: Enable LDP IGP synchronization.
                        type: bool
                      sync_igp_shortcuts:
                        description: LDP sync for igp-shortcut tunnels.
                        type: bool  
              mtu_ignore:
                description: Enable/Disable ignoring of MTU in DBD packets.
                type: str
                choices:
                  - enable
                  - disable
              bfd:
                description: Configure BFD parameters.
                type: dict
                suboptions:
                fast_detect:
                  description: Configure fast detection.
                  type: dict
                  suboptions:
                    set:
                      description: Enable fast detection only.
                      type: bool
                    strict_mode:
                      description: Hold down neighbor session until BFD session is up.
                      type: bool
                minimum_interval:
                  description: Hello interval in milli-seconds.
                  type: int
                multiplier:
                  description: Detect multiplier.
                  type: int
              nssa:
                description:
                  - NSSA settings for the area.
                type: dict
                suboptions:
                  set:
                    description: Configure area as NSSA.
                    type: bool
                  default_information_originate:
                    description: Originate default Type 7 LSA.
                    type: dict
                    suboptions:
                      metric:
                        description: OSPF default metric.
                        type: int
                      metric_type:
                        description: Metric type for default routes.
                        type: int
                  no_redistribution:
                    description: Do not send redistributed LSAs into NSSA area.
                    type: bool
                  no_summary:
                    description: Do not send summary LSAs into NSSA area.
                    type: bool
                  translate:
                    description: Translate LSA.
                    type: dict
                    suboptions:
                      type7:
                        description:
                          - Translate from Type 7 to Type 5.
                        type: dict
                        suboptions:
                          always:
                            description:
                              - Always translate LSAs
                            type: bool
              ranges:
                description: Summarize routes matching address/mask (border routers only).
                type: list
                elements: dict
                suboptions:
                  address:
                    description: IP in Prefix format (x.x.x.x/len)
                    type: str
                    required: True
                  advertise:
                    description: Advertise this range (default)
                    type: bool
                  not_advertise:
                    description: DoNotAdvertise this range
                    type: bool
              route_policy:
                description: Specify the route-policy to filter type 3 LSAs (list can have one inbound and/or one outbound policy only).
                type: list
                elements: dict
                suboptions:
                  parameters:
                    description: Specify parameter values for the policy
                    type: list
                    elements: str
                  direction:
                    description: Specify inbound or outbound
                    type: str
                    choices:
                      - in
                      - out
              stub:
                description:
                  - Settings for configuring the area as a stub.
                type: dict
                suboptions:
                  set:
                    description:
                      - Configure the area as a stub.
                    type: bool
                  no_summary:
                    description:
                      - Do not send summary LSA into stub area.
                    type: bool
              virtual_link:
                description: Define a virtual link.
                type: list
                elements: dict
                suboptions:
                  id:
                    description: Router-ID of virtual link neighbor (A.B.C.D).
                    type: str
                    required: True
                  authentication:
                    description: Enable authentication
                    type: dict
                    suboptions:
                      keychain:
                        description: Specify keychain name
                        type: str
                      message_digest:
                        description: Use message-digest authentication
                        type: dict
                        suboptions:
                          keychain:
                            description: Specify keychain name
                            type: str
                      no_auth:
                        description: Use no authentication
                        type: bool
                  authentication_key:
                    description: Used to mention authentication password (key).
                    type: dict
                    suboptions:
                      password:
                        description: The OSPF password (key)
                        type: str
                      clear:
                        description: Specifies an UNENCRYPTED password (key) will follow
                        type: str
                      encrypted:
                        description: Specifies an ENCRYPTED password (key) will follow
                        type: str
                  dead_interval:
                    description: Interval after which a neighbor is declared dead (<1-65535> seconds).
                    type: int
                  hello_interval:
                    description: Time between HELLO packets (<1-65535> seconds).
                    type: int
                  retransmit_interval:
                    description: Delay between LSA retransmissions (<1-65535> seconds).
                    type: int
                  transmit_delay:
                    description: Link state transmit delay (<1-65535> seconds).
                    type: int
                  message_digest_key:
                    description: Message digest authentication password (key)
                    type: dict
                    suboptions:
                      id:
                        description: Key ID (1-255)
                        type: int
                        required: True
                      md5:
                        description: Use MD5 Algorithm
                        type: dict
                        suboptions:
                          password:
                            description: The OSPF password (key)
                            type: str
                          clear:
                            description: Specifies an UNENCRYPTED password (key) will follow
                            type: bool
                          encrypted:
                            description: Specifies an ENCRYPTED password (key) will follow
                            type: bool       
              
          authentication_key:
            description: Used to mention authentication password (key).
            type: dict
            suboptions:
              password:
                description: The OSPF password (key).
                type: str
              clear:
                description: Specifies an UNENCRYPTED password (key) will follow.
                type: bool
              encrypted:
                description: Specifies an ENCRYPTED password (key) will follow.
                type: bool
          auto_cost:
            description: Calculate OSPF interface cost according to bandwidth.
            type: dict
            suboptions:
              reference_bandwidth:
                description: Specify reference bandwidth in megabits per sec.
                type: int
              disable:
                description: Assign OSPF cost based on interface type
                type: bool
          bfd:
            description: Configure BFD parameters.
            type: dict
            suboptions:
              fast_detect:
                description: Configure fast detection.
                type: dict
                suboptions:
                  set:
                    description: Enable fast detection only.
                    type: bool
                  strict_mode:
                    description: Hold down neighbor session until BFD session is up.
                    type: bool
              minimum_interval:
                description: Hello interval in milli-seconds   (50-30000).
                type: int
              multiplier:
                description: Detect multiplier (3-50)
                type: int
          capability:
            description: Enable specific OSPF feature.
            type: dict
            suboptions:
              type7:
                description: NSSA capability.
                type: str
              opaque:
                description: Configure opaque LSA.
                type: dict
                suboptions:
                  disable: 
                    description: Disable Opaque LSA capability.
                    type: bool
                  set:
                    description: Enable opaque LSA.
                    type: bool
          cost:
            description: Interface cost (1-65535).
            type: int
          database_filter:
            description: Filter OSPF LSA during synchronization and flooding (all outgoing LSA). Enable/Disable filtering.
            type: str
            choices: ['enable','disable']
          dead_interval:
            description: Interval after which a neighbor is declared dead (<1-65535> seconds).
            type: int
          default_information_originate:
            description: Distribute default route.
            type: dict
            suboptions:
              always:
                description: Always advertise default route.
                type: bool
              metric:
                description: OSPF default metric <1-16777214>.
                type: int
              metric_type:
                description: OSPF metric type for default routes.
                type: int
              route_policy:
                description: Apply route-policy to default-information origination.
                type: str
              set:
                description: Enable distribution of default route.
                type: bool
          default_metric:
            description: Set metric of redistributed routes <1-16777214>.
            type: int
          demand_circuit:
            description: Enable/Disable OSPF demand circuit.
            type: str
            choices: ['enable','disable']
          distance:
            description: Define an administrative distance.
            type: dict
            suboptions:
              admin_distance:
                description: Administrative distance.
                type: list
                elements: dict
                suboptions:
                  value:
                    description: Distance value (1-255).
                    type: int
                  source:
                    description: Source IP address.
                    type: str
                  wildcard:
                    description: IP wild card bits (A.B.C.D).
                    type: str
                  access_list:
                    description: Access list name.
                    type: str
              ospf_distance:
                description: OSPF administrative distance.
                type: dict
                suboptions:
                  external: 
                    description: Distance for external routes.
                    type: int
                  inter_area:
                    description: Distance for inter-area routes.
                    type: int
                  intra_area:
                    description: Distance for intra-area routes.
                    type: int 
          distribute_link_state:
            description: Enable Distribution of LSAs to external services.
            type: dict
            suboptions:
              instance_id:
                description: Set distribution process instance identifier <0-4294967295>.
                type: int
              throttle:
                description: Throttle time between successive LSA updates (<1-3600> seconds).
                type: int
          distribute_list:
            description: Filter networks in routing updates (list can have one inbound and/or one outbound policy only).
            type: list
            elements: dict
            suboptions:
              access_list:
                description: Inbound/outbound access-list.
                type: str
              direction:
                description: Filter incoming/outgoing routing updates
                type: str
                choices:
                  - in
                  - out
              outgoing_params:
                description: Specify additional parameters for outgoing updates only.
                type: dict
                suboptions:
                  route_type:
                    description: Type of routes.
                    type: str
                    choices: 
                      - bgp
                      - connected
                      - dagr
                      - ospf
                      - static
                  id: 
                    description:
                      - For BGP, specify AS number. 2-byte AS number <1-65535> (or) 4-byte AS number in asdot (X.Y) format <1-65535>.<0-65535> (or) 4-byte AS number in asplain format <65536-4294967295>.
                      - For OSPF, specify OSPF instance name.
                    type: str
              route_policy:
                description: Route Policy to filter OSPF prefixes (for incoming updates only).
                type: str
          external_out:
            description: Enable/Disable advertisement of intra-area prefixes as external
            type: str
            choices:
              - enable
              - disable
          flood_reduction:
            description: Enable/Disable OSPF Flood Reduction.
            type: str
            choices:
              - enable
              - disable                    
          hello_interval:
            description: Time between HELLO packets (<1-65535> seconds).
            type: int
          ignore_lsa_mospf:
            description: Do not complain upon receiving MOSPF Type 6 LSA.
            type: bool
          link_down_fast_detect:
            description: Enable fast or early detection of link-down events.
            type: bool
          log_adjacency_changes:
            description: Log adjacency state changes.
            type: dict
            suboptions:
              disable:
                description: Disable log adjacency changes.
                type: bool
              detail:
                description: Log all state changes.
                type: bool
          loopback_stub_network:
            description: Advertise loopback as a stub network.
            type: str
            choices:
              - enable
              - disable
          max_lsa:
            description:
              - Feature to limit the number of non-self-originated LSAs.
            type: dict
            suboptions:
              threshold:
                description:
                  - Threshold value (%) at which to generate a warning message.
                type: int
              ignore_count:
                description:
                  - Set count on how many times adjacencies can be suppressed <1-4294967294>.
                type: int
              ignore_time:
                description:
                  - Set number of minutes during which all adjacencies are suppressed <1-35791394>.
                type: int
              reset_time:
                description:
                  - Set number of minutes after which ignore-count is reset to zero <2-71582788>.
                type: int
              warning_only:
                description:
                  - Log a warning message when limit is exceeded.
                type: bool
          max_metric:
            description: Set maximum metric.
            type: dict
            suboptions:
              router_lsa:
                description: Maximum metric in self-originated router-LSAs.
                type: dict
                suboptions:
                  set:
                    description: Set router-lsa attribute.
                    type: bool
                  external_lsa:
                    description: External LSA configuration.
                    type: dict
                    suboptions:
                      set:
                        description: Set external-lsa attribute.
                        type: bool
                      max_metric_value:
                        description: Set max metric value for external LSAs.
                        type: int
                  include_stub:
                    description:
                      - Advertise Max metric for Stub links as well.
                    type: bool
                  on_startup:
                    description:
                      - Effective only at startup.
                    type: dict
                    suboptions:
                      set:
                        description:
                          - Set on-startup attribute.
                        type: bool
                      wait_period:
                        description:
                          - Wait period in seconds after startup.
                        type: int
                      wait_for_bgp_asn:
                        description:
                          - ASN of BGP to wait for.
                        type: int
                  summary_lsa:
                    description:
                      - Summary LSAs configuration.
                    type: dict
                    suboptions:
                      set:
                        description:
                          - Set summary-lsa attribute.
                        type: bool
                      max_metric_value:
                        description:
                          - Max metric value for summary LSAs.
                        type: int
          maximum:
            description: Set OSPF limits.
            type: dict
            suboptions:
              interfaces:
                description:  Limit number of interfaces <1-4294967295>.
                type: int
              paths:
                description:  Limit number of paths <1-64>. 
                type: int
              redistributed_prefixes:
                description:  Limit number of redistributed prefixes.
                type: dict
                suboptions:
                  prefixes:
                    description: Maximum number of prefixes redistributed into OSPF <1-4294967295>.
                    type: int
                    required: True
                  threshold:
                    description: Threshold value (%) at which to generate a warning message.
                    type: int
                  warning_only:
                    description: Only give warning messsage when limit is exceeded.
                    type: bool     
          message_digest_key:
            description: Message digest authentication password (key)
            type: dict
            suboptions:
              id:
                description: Key ID (1-255)
                type: int
                required: True
              md5:
                description: Use MD5 Algorithm
                type: dict
                required: True
                suboptions:
                  password:
                    description: The OSPF password (key)
                    type: str
                  clear:
                    description: Specifies an UNENCRYPTED password (key) will follow
                    type: bool
                  encrypted:
                    description: Specifies an ENCRYPTED password (key) will follow
                    type: bool            
          microloop_avoidance:
            description: Avoid microloops.
            type: dict
            suboptions:
              protected:
                description: Avoid microloops for protected prefixes only).
                type: bool
              rib_update_delay:
                description: Delay to introduce between SPF and RIB updates (<1-600000> milliseconds).
                type: int
              segment_routing:
                description: Enable segment routing microloop avoidance.
                type: bool
          monitor_convergence:
            description: Enables OSPF route convergence monitoring.
            type: dict
            suboptions:
              prefix_list:
                description: Enables Individual Prefix Monitoring.
                type: str
              track_external_routes:
                description: Enables Tracking External(Type-5/7) Prefix monitoring.
                type: bool
              track_ip_frr: 
                description: Enables Tracking IP-Frr Convergence.
                type: bool
              track_summary_routes:
                description: Enables Tracking Summary(Inter-Area) Prefix monitoring.
                type: bool
          mpls:
            description: Configure MPLS routing protocol parameters.
            type: dict
            suboptions:
              ldp:
                description: Configure LDP parameters.
                type: dict
                suboptions:
                  auto_config:
                    description: Enable LDP IGP interface auto-configuration.
                    type: bool
                  sync:
                    description: Enable LDP IGP synchronization.
                    type: bool
                  sync_igp_shortcuts:
                    description: LDP sync for igp-shortcut tunnels.
                    type: bool
              traffic_eng:
                  description: Routing protocol commands for MPLS Traffic Engineering.
                  type: dict
                  suboptions:
                    autoroute_exclude:
                      description: Exclude IP address destinations from using TE tunnels.
                      type: dict
                      suboptions:
                        route_policy:
                          description: Policy name.
                          type: str
                        parameters:
                          description: Specify parameter values for the policy.
                          type: list
                          elements: str
                    igp_intact:
                      description: Retain one or more IPv4 nexthops with tunnel nexthops.
                      type: bool
                    ldp_sync_update:
                      description: Enable LDP sync induced metric propagation.
                      type: bool
                    multicast_intact:
                      description: Publish multicast-intact paths to RIB.
                      type: bool
                    router_id:
                      description: Traffic Engineering stable IP address for system.
                      type: str
          mtu_ignore:
            description: Enable/Disable ignoring of MTU in DBD packets.
            type: str
            choices:
              - enable
              - disable
          network:
            description: Network type.
            type: dict
            suboptions:
              broadcast:
                description: Specify OSPF broadcast multi-access network.
                type: bool
              non_broadcast:
                description: Specify OSPF NBMA network.
                type: bool
              point_to_multipoint:
                description: Specify OSPF point-to-multipoint network.
                type: bool
              point_to_point:
                description: Specify OSPF point-to-point network.
                type: bool
          nsf:
            description: Non-stop forwarding.
            type: dict
            suboptions:
              cisco:
                description: Cisco Non-stop forwarding.
                type: dict
                suboptions:
                  enforce_global:
                    description: Cancel NSF restart when non-NSF-aware neighbors detected for the whole OSPF process.
                    type: bool
                  set:
                    description: Enable Cisco NSF.
                    type: bool
              flush_delay_time:
                description: Maximum time allowed for external route learning (<1-3600> seconds).
                type: int
              ietf:
                description: IETF graceful restart.
                type: dict
                suboptions:
                  helper_disable:
                    description: Disable router's helper support level.
                    type: bool
                  set:
                    description: Only enable ietf option.
                    type: bool
              interval:
                description: Minimum interval between NSF restarts (<90-3600> seconds).
                type: int            
              lifetime:
                description:  Maximum route lifetime following restart (<90-1800> seconds).
                type: int
          nsr:
            description: Enable NSR for all VRFs in this process. 'False' option to disable NSR for all VRFs in this process.
            type: bool
          packet_size:
            description: Size of OSPF packets to use. min=576 max=MTU bytes.
            type: int
          passive:
            description: Enable/Disable passive.
            type: str
            choices:
              - enable
              - disable
          prefix_suppression:
            description: Suppress advertisement of the prefixes.
            type: dict
            suboptions:
              set:
                description: Set the suppression option.
                type: bool
              secondary_address:
                description: Enable/Disable secondary address suppression.
                type: bool
          priority:
            description: Router priority <0-255>.
            type: int
          process_id:
            description: The OSPF Process ID.
            type: str
            required: True
          protocol_shutdown:
            description: Protocol specific configuration
            type: dict
            suboptions:
              host_mode:
                description: Only traffic destined for this box allowed(cisco-support).
                type: bool
              on_reload:
                description: Shutdown post reload only.
                type: bool
              set:
                description: Shutdown the OSPF Protocol.
                type: bool
          queue:
            description: Adjust OSPF input queue.
            type: dict
            suboptions:
              dispatch: 
                description: Number of continuous events processed by type.
                type: dict
                suboptions:
                  flush_lsa:
                    description: Maximum number of LSAs flushed per run <30-3000>.
                    type: int
                  incoming:
                    description: Maximum number of continuous incoming events processed <30-3000>.
                    type: int
                  rate_limited_lsa:
                    description: Maximum number of rate-limited LSAs processed <30-3000>.
                    type: int
                  spf_lsa_limit:
                    description: Maximum number of summary or external LSAs processed per run <30-3000>.
              limit:
                description: High watermark for incoming priority events.
                type: dict
                suboptions:
                  high:
                    description: Hello events are dropped when incoming event queue exceeds this value <1000-30000>.
                    type: int
                  low:
                    description: DBD/LS Update/Req packets are dropped when incoming event queue exceeds this value <1000-30000>.
                    type: int
                  medium:
                    description: LSA ACKs are dropped when incoming event queue exceeds this value <1000-30000>.
                    type: int
          redistribute:
            description: Redistribute information from another routing Protocol.
            type: dict
            suboptions:
              route_type:
                description: Route type to redistribute.
                type: str
                choices: ['application', 'bgp', 'connected', 'dagr', 'eigrp', 'isis', 'mobile', 'ospf', 'rip', 'static', 'subscriber']
              id:
                description: OnePK application name for application routes (or) AS number for bgp and eigrp (or) instance name for isis and ospf.
                type: str
              level:
                description: ISIS levels.(1=level-1 routes only, 2=level-2 routes only,12=level-1 and level-2 routes)
                choices: [1,2,12]
                type: int
              lsa_type_summary:
                description: LSA type 3 for redistributed routes.
                type: bool
              match:
                description: Redistribution of routes. For OSPF - external/internal/nssa-external 1/2. For EIGRP - external/internal.
                type: str
              metric:
                description: Metric for redistributed routes.
                type: int
              metric_type:
                description: OSPF exterior metric type for redistributed routes (Type 1/Type 2). 
                type: int
                choices: [1,2]
              route_policy:
                description: Apply route-policy to redistribution.
                type: dict
                suboptions:
                  name:
                    description: Name of the policy.
                    type: str
                  parameters:
                    description: Specify parameter values for the policy.
                    type: list
                    elements: str                
              nssa_only:
                description: Redistribute to NSSA areas only.
                type: bool
              preserve_med:
                description: Preserve med of BGP routes.
                type: bool
              tag:
                description: Set tag for routes redistributed into OSPF <0-4294967295>.
                type: int
          retransmit_interval:
            description: Delay between LSA retransmissions (<1-65535> seconds).
            type: int
          router_id:
            description: OSPF router-id in IPv4 address format (A.B.C.D).
            type: str
          security_ttl:
            description: Enable security.
            type: dict
            suboptions:
              set:
                description: Enable ttl security.
                type: bool
              hops:
                description: Maximum number of IP hops allowed <1-254>.
                type: int
          segment_routing:
            description: Segment Routing configuration.
            type: dict
            suboptions:
              disable:
                description: Disable Segment Routing.
                type: bool
              forwarding:
                description: disable - Disable Segment-routing on process interfaces. mpls - Use MPLS for Segment-routing forwarding.
                type: str
                choices: ['disable','mpls']
              global_block:
                description: MPLS label range for SID allocation.
                type: dict
                suboptions:
                  min:
                    description: Minimum MPLS label value for Segment Routing <16000-1048575>.
                    type: int
                  max:
                    description: Maximum MPLS label value for Segment Routing <112132-1048575>.
                    type: int
              mpls:
                description: SR using MPLS dataplane.
                type: bool
              prefix_sid_map:
                description: Configuring segment routing mapping server. 'advertise_local' - Advertise and use local mapping server entries. 'receive_disable' - Disable the usage of remote mapping server advertisements.
                type: str
                choices: ['advertise_local','receive_disable']
              sr_prefer:
                description: Filter prefixes for which SR preference is applied. Prefix-list name.
                type: str
          snmp:
            description: SNMP configuration.
            type: dict
            suboptions:
              context:
                description: SNMP context name.
                type: str
              trap_rate_limit:
                description: Adjust trap rate-limit parameters.
                type: dict
                suboptions:
                  size:
                    description: Trap rate limit sliding window size <2-60>.
                    type: int
                  max:
                    description: Max number of traps sent in window time <0-300>.
                    type: int
          spf_prefix_priority:
            description: Configure SPF prefix priority route policy
            type: dict
            suboptions:
              route_policy:
                description: Specify the route-policy name to prioritize route install.
                type: str
              parameters:
                description: Specify parameter values for the policy.
                type: list
                elements: str
          summary_in:
            description: Enable/Disable advertisement of external prefixes as inter-area.
            type: str
            choices: ['enable','disable']
          summary_prefix:
            description: Configure IP address summaries.
            type: list
            elements: dict
            suboptions:
              prefix:
                description: IP summary address/mask (A.B.C.D/prefix).
                type: str
                required: True
              not_advertise:
                description: Suppress routes that match the specified prefix/mask pair.
                type: bool
              tag:
                description: Set tag <0-4294967295>.
                type: int
          timers:
            description: Configure timer related constants.
            type: dict
            suboptions:
              graceful_shutdown:
                description: Timers for graceful shutdown(cisco-support).
                type: dict
                suboptions:
                  initial_delay:
                    description: Delay before starting graceful shutdown (<0-90> seconds).
                    type: int
                  retain_routes:
                    description: Time to keep routes active after graceful shutdown (<0-90> seconds).
                    type: int
              lsa:
                description: OSPF global LSA timers
                type: dict
                suboptions:
                  group_pacing:
                    description: OSPF LSA group pacing timer. Interval between group of LSA being refreshed or maxaged <10-1800>.
                    type: int
                  min_arrival:
                    description: OSPF MinLSArrival timer. The minimum interval in millisec between accepting the same LSA <0-600000>.
                    type: int
                  refresh:
                    description: OSPF LSA refresh interval. How often self-originated LSAs should be refreshed, in seconds <1800-2700>.
              throttle:
                description: OSPF throttle timers.
                type: dict
                suboptions:
                  lsa_all:
                    description: LSA throttle timers for all types of OSPF LSAs.
                    type: dict
                    suboptions:
                      initial_delay:
                        description: Delay to generate first occurance of LSA in milliseconds <0-600000>.
                        type: int
                      min_delay:
                        description: Minimum delay between originating the same LSA in milliseconds <1-600000>.
                        type: int
                      max_delay:
                        description: Maximum delay between originating the same LSA in milliseconds <1-600000>.
                        type: int
                  spf:
                    description: OSPF SPF throttle timers.
                    type: dict
                    suboptions:
                      change_delay:
                        description: Delay between receiving a change to SPF calculation in milliseconds <1-600000>.
                        type: int
                      second_delay:
                        description: Delay between first and second SPF calculation in milliseconds <1-600000>.
                        type: int
                      max_wait:
                        description: Maximum wait time in milliseconds for SPF calculations <1-600000>.
                        type: int
                  fast_reroute:
                    description: Fast-reroute throttle timer. Delay between end of SPF and start of the fast-reroute computation in milliseconds <50-600000>.
                    type: int
              pacing_flood:
                description: OSPF flood pacing timer. Interval in msec to pace flooding on all interfaces <5-100>.
                type: int
          trace:
            description: OSPF tracing options(cisco-support).
            type: dict
            suboptions:
              name:
                description: Name of trace buffer.
                type: str
              entry:
                description: Trace entries (0-disbale trace).
                type: int
                choices: [0,256,512,1024,2048,4096,8192,16384,32768,65536]
          transmit_delay:
            description: Estimated time needed to send link-state update packet (<1-65535> seconds).
            type: int
          ucmp:
            description: Configure Unequal Cost Load Balancing.
            type: dict
            suboptions:
              delay_interval:
                description: Interval between SPF and start of the UCMP calculation (<1-5000> milliseconds).
                type: int
              prefix_list:
                description: Filter prefixes for which UCMP path are calculated. Prefix-list name.
                type: str
              variance:
                description: Set the Variance for UCMP path metric. Percentage of the primary path metric <101-10000>.
                type: int
              exclude:
                description: UCMP exclusion information.
                type: dict
                suboptions:
                  interface_type:
                    description: Exclude an interface during UCMP computation. Refer vendor documentation for respective valid values.
                    type: str
                  interface:
                    description: Refer vendor documentation for respective valid values of different interfaces.
                    type: str                             
              set:
                description: Set the UCMP feature.
                type: bool
          weight:
            description: Interface weight <1-16777214>.
            type: int
  state:
    description:
      - The state the configuration should be left in.
    type: str
    choices:
      - merged
      - replaced
      - overridden
      - deleted
      - gathered
      - rendered
      - parsed
    default: merged
"""
EXAMPLES = """
# Using merged
#
#
# -------------
# Before State
# -------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 19:27:54.933 UTC
# % No such configuration item(s)
#
# 

- name: Merge provided LLDP configuration with the existing configuration
  iosxr_lldp_global:
    config:
      holdtime: 100
      reinit: 2
      timer: 3000
      subinterfaces: enable
      tlv_select:
        management_address: False
        system_description: False
    state: merged

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {}
#  
#  "commands": [
#        "lldp subinterfaces enable",
#        "lldp holdtime 100",
#        "lldp reinit 2",
#        "lldp tlv-select system-description disable",
#        "lldp tlv-select management-address disable",
#        "lldp timer 3000"
#  ]
#
#  "after": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  }
#
#
# ------------
# After state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#


# Using deleted
#
# ------------
# Before state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#

- name: Deleted existing LLDP configurations from the device
  iosxr_lldp_global:
    state: deleted

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  },
#  
#  "commands": [
#        "no lldp holdtime 100",
#        "no lldp reinit 2",
#        "no lldp subinterfaces enable",
#        "no lldp timer 3000",
#        "no lldp tlv-select management-address disable",
#        "no lldp tlv-select system-description disable"
#  ]
#  
#  "after": {}
#
#
# -----------
# After state
# -----------
# 
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:38:31.187 UTC
# lldp
# !
#
#


# Using deleted
#
# ------------
# Before state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#

- name: Deleted existing LLDP configurations from the device
  iosxr_lldp_global:
    state: deleted

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  },
#  
#  "commands": [
#        "no lldp holdtime 100",
#        "no lldp reinit 2",
#        "no lldp subinterfaces enable",
#        "no lldp timer 3000",
#        "no lldp tlv-select management-address disable",
#        "no lldp tlv-select system-description disable"
#  ]
#  
#  "after": {}
#
#
# -----------
# After state
# -----------
# 
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:38:31.187 UTC
# lldp
# !
#
#


# Using deleted
#
# ------------
# Before state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#

- name: Deleted existing LLDP configurations from the device
  iosxr_lldp_global:
    state: deleted

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  },
#  
#  "commands": [
#        "no lldp holdtime 100",
#        "no lldp reinit 2",
#        "no lldp subinterfaces enable",
#        "no lldp timer 3000",
#        "no lldp tlv-select management-address disable",
#        "no lldp tlv-select system-description disable"
#  ]
#  
#  "after": {}
#
#
# -----------
# After state
# -----------
# 
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:38:31.187 UTC
# lldp
# !
#
#


# Using deleted
#
# ------------
# Before state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#

- name: Deleted existing LLDP configurations from the device
  iosxr_lldp_global:
    state: deleted

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  },
#  
#  "commands": [
#        "no lldp holdtime 100",
#        "no lldp reinit 2",
#        "no lldp subinterfaces enable",
#        "no lldp timer 3000",
#        "no lldp tlv-select management-address disable",
#        "no lldp tlv-select system-description disable"
#  ]
#  
#  "after": {}
#
#
# -----------
# After state
# -----------
# 
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:38:31.187 UTC
# lldp
# !
#
#


# Using deleted
#
# ------------
# Before state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#

- name: Deleted existing LLDP configurations from the device
  iosxr_lldp_global:
    state: deleted

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  },
#  
#  "commands": [
#        "no lldp holdtime 100",
#        "no lldp reinit 2",
#        "no lldp subinterfaces enable",
#        "no lldp timer 3000",
#        "no lldp tlv-select management-address disable",
#        "no lldp tlv-select system-description disable"
#  ]
#  
#  "after": {}
#
#
# -----------
# After state
# -----------
# 
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:38:31.187 UTC
# lldp
# !
#
#


# Using deleted
#
# ------------
# Before state
# ------------
#
#
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:31:10.587 UTC
# lldp
#  timer 3000
#  reinit 2
#  subinterfaces enable
#  holdtime 100
#  tlv-select
#   management-address disable
#   system-description disable
#  !
# !
#
#

- name: Deleted existing LLDP configurations from the device
  iosxr_lldp_global:
    state: deleted

#
#
# ------------------------
# Module Execution Result
# ------------------------
#
#  "before": {
#        "holdtime": 100,
#        "reinit": 2,
#        "subinterfaces": true,
#        "timer": 3000,
#        "tlv_select": {
#            "management_address": false,
#            "system_description": false
#        }
#  },
#  
#  "commands": [
#        "no lldp holdtime 100",
#        "no lldp reinit 2",
#        "no lldp subinterfaces enable",
#        "no lldp timer 3000",
#        "no lldp tlv-select management-address disable",
#        "no lldp tlv-select system-description disable"
#  ]
#  
#  "after": {}
#
#
# -----------
# After state
# -----------
# 
# RP/0/0/CPU0:an-iosxr#sh run lldp
# Tue Aug  6 21:38:31.187 UTC
# lldp
# !
#
#


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.cisco.iosxr.plugins.module_utils.network.iosxr.argspec.ospfv2.ospfv2 import (
    Ospfv2Args,
)
from ansible_collections.cisco.iosxr.plugins.module_utils.network.iosxr.config.ospfv2.ospfv2 import (
    Ospfv2,
)


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [
        ("state", "merged", ("config",)),
        ("state", "replaced", ("config",)),
        ("state", "overridden", ("config",)),
        ("state", "rendered", ("config",)),
        ("state", "parsed", ("running_config",)),
    ]
    mutually_exclusive = [("config", "running_config")]
    module = AnsibleModule(
        argument_spec=Ospfv2Args.argument_spec,
        required_if=required_if,
        supports_check_mode=True,
        mutually_exclusive=mutually_exclusive,
    )
    result = Ospfv2(module).execute_module()
    module.exit_json(**result)


if __name__ == "__main__":
    main()
