---
name: integration-simple
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  create_lab:
    uses: ansible/ansible-content-actions/.github/workflows/cml_lab_create.yaml@main
    with:
      cml_user: ${{ secrets.CML_USER }}
      cml_password: ${{ secrets.CML_PASSWORD }}
      cml_server: ${{ secrets.CML_SERVER }}
      cml_lab_name: "cisco.iosxr-ci"
      cml_topology: "tests/integration/labs/multi.yaml"

  run_tests:
    needs: create_lab
    uses: ansible/ansible-content-actions/.github/workflows/network_simple.yaml@main
    with:
      cml_user: ${{ secrets.CML_USER }}
      cml_password: ${{ secrets.CML_PASSWORD }}
      cml_server: ${{ secrets.CML_SERVER }}
      cml_lab_name: "cisco.iosxr-ci"
      inventory_template: "tests/integration/labs/inventory.j2"
      ansible_extra_options: "-e ansible_network_os=cisco.iosxr.iosxr"
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git

  destroy_lab:
    if: always()
    needs: [create_lab, run_tests]
    uses: ansible/ansible-content-actions/.github/workflows/cml_lab_destroy.yaml@main
    with:
      cml_user: ${{ secrets.CML_USER }}
      cml_password: ${{ secrets.CML_PASSWORD }}
      cml_server: ${{ secrets.CML_SERVER }}
      cml_lab_name: "cisco.iosxr-ci"
